version: '3.1'

services:

  bag3d_db:
    image: postgis/postgis:12-3.0
    working_dir: /tmp
    ports:
    - "5590:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test_admin
    volumes:
    - ./bag3d_db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    - ./bag3d_db/bag3d_db.dump:/tmp/bag3d_db.dump
