type: map
mapping:
    database:
        desc: Database connection parameters
        type: map
        mapping:
            dbname:
                type: str
                required: True
            host:
                type: str
                required: True
            port:
                type: int
                required: True
            user:
                type: str
                required: True
            password:
                type: str

    features:
        type: map
        mapping:
            schema:
                type: str
                required: True
            table:
                type: str
                required: True
            field:
                type: map
                mapping:
                    pk:
                        type: str
                        required: True
                        desc: Name of the primary key field
                    geometry:
                        type: str
                        required: True
                        desc: Name of the geometry field
                    uniqueid:
                        type: str
                        required: True
                        desc: Not sure myself

    features_index:
        type: map
        mapping:
            schema:
                type: str
                required: True
            table:
                type: str
                required: True
